version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: Visual Studio 15 2017 Win64

before_build:
  - cmake -Bbuild -Hexample -G "%GENERATOR%"

build_script:
  - cmake --build build

test_script:
  - build\Debug\main.exe
